[build]
builder = "nixpacks"

[[build.env]]
NIXPACKS_PLAN_PROVIDERS = "node"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3002"